databaseType = "MySql"
id = "e966a59a-143a-4cf4-a266-0787f5257eb7"
name = "travel-order"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
enableMigrations = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target1]
url = "jdbc:mysql://localhost"
user = "root"
schemas = [ "travel_test" ]

[environments.travelorder]
url = "jdbc:mysql://localhost"
schemas = [ "travel_order" ]
displayName = "Travel Order"
